apiVersion: v1
kind: Pod
metadata: 
  name: example-node-affinity-hard
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disk
                operator: In
                values:
                - ssd
  containers:
  - name:  example-node-affinity-hard
    image: nginx
