apiVersion: v1
kind: Pod
metadata: 
  name:  example-node-affinity-hard-notin
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disk
                operator: NotIn
                values:
                - ssd
  containers:
  - name: example-node-affinity-hard-notin
    image: nginx
