apiVersion: v1
kind: Pod
metadata:
  name: practice-3-1-backend
spec:
  containers:
  - name: practice-3-1-backend
    image: ghcr.io/albertoig/cka-certification/certification/3-servicing-and-networking/practices/code/3-backend:0.0.2
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
    resources:
      requests:
        memory: "512Mi"
        cpu: "150m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
