apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-3-1-backend
  labels:
    app: practice-3-1-backend
spec:
  selector:
    matchLabels:
      app: practice-3-1-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: practice-3-1-backend
    spec:
      containers:
      - name: practice-3-1-backend
        image: ghcr.io/albertoig/cka-certification/certification/3-servicing-and-networking/practices/code/3-backend:0.0.1
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
