name: Docker Build and Push Multiple Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  packages: write 

jobs:
  build-and-push:
    strategy:
      matrix:
        service:
          - path: certification/3-servicing-and-networking/practices/code/3-backend
            dockerfile: Dockerfile
          - path: certification/3-servicing-and-networking/practices/code/3-frontend
            dockerfile: Dockerfile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for ${{ matrix.service.path }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.path }}
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ matrix.service.path }}:0.0.2
        file: ${{ matrix.service.path }}/${{ matrix.service.dockerfile }}
